import { hexToRgb, normalizeHex, rgbToLab } from "./color";
import type { PaletteColor, PaletteSeed } from "./types";

export function preparePalette(colors: PaletteSeed[]): PaletteColor[] {
  return colors.map((color, index) => {
    const hex = normalizeHex(color.hex);
    const rgb = hexToRgb(hex);

    return {
      id: color.code,
      brand: "MARD",
      code: color.code,
      nameZh: color.nameZh,
      nameEn: color.nameEn,
      hex,
      rgb,
      lab: rgbToLab(rgb),
      isAvailable: true,
      sortOrder: index
    };
  });
}

// 完整 MARD 色卡（291 色）。色号与 HEX 取自官方色号表
// （https://www.pixel-beads.com/zh/mard-bead-color-chart），权威可用于配色与采购。
// 中文色名为便于阅读统计表/导出文件的参考名，按色相语义标注，下单前请以官方为准。
export const MARD_PALETTE_SEEDS: PaletteSeed[] = [
  { code: "T1", nameZh: "白色", hex: "#ffffff" },
  // A：黄 / 橙
  { code: "A1", nameZh: "米黄", hex: "#faf4c8" },
  { code: "A2", nameZh: "浅奶黄", hex: "#ffffd5" },
  { code: "A3", nameZh: "嫩黄", hex: "#feff8b" },
  { code: "A4", nameZh: "柠檬黄", hex: "#fbed56" },
  { code: "A5", nameZh: "金黄", hex: "#f4d738" },
  { code: "A6", nameZh: "杏橙", hex: "#feac4c" },
  { code: "A7", nameZh: "橘色", hex: "#fe8b4c" },
  { code: "A8", nameZh: "鲜黄", hex: "#ffda45" },
  { code: "A9", nameZh: "浅橘", hex: "#ff995b" },
  { code: "A10", nameZh: "深橘", hex: "#f77c31" },
  { code: "A11", nameZh: "奶油橘", hex: "#ffdd99" },
  { code: "A12", nameZh: "蜜桃橘", hex: "#fe9f72" },
  { code: "A13", nameZh: "蜜黄", hex: "#ffc365" },
  { code: "A14", nameZh: "朱红", hex: "#fd543d" },
  { code: "A15", nameZh: "鹅黄", hex: "#fff365" },
  { code: "A16", nameZh: "月光黄", hex: "#ffff9f" },
  { code: "A17", nameZh: "雏菊黄", hex: "#ffe36e" },
  { code: "A18", nameZh: "杏色", hex: "#febe7d" },
  { code: "A19", nameZh: "珊瑚红", hex: "#fd7c72" },
  { code: "A20", nameZh: "向日黄", hex: "#ffd568" },
  { code: "A21", nameZh: "浅奶油", hex: "#ffe395" },
  { code: "A22", nameZh: "柔黄", hex: "#f4f57d" },
  { code: "A23", nameZh: "米肤", hex: "#e6c9b7" },
  { code: "A24", nameZh: "浅鹅黄", hex: "#f7f8a2" },
  { code: "A25", nameZh: "浅杏黄", hex: "#ffd67d" },
  { code: "A26", nameZh: "蛋黄", hex: "#ffc830" },
  // B：绿
  { code: "B1", nameZh: "黄绿", hex: "#e6ee31" },
  { code: "B2", nameZh: "嫩绿", hex: "#63f347" },
  { code: "B3", nameZh: "浅葱绿", hex: "#9ef780" },
  { code: "B4", nameZh: "草绿", hex: "#5de035" },
  { code: "B5", nameZh: "翠绿", hex: "#35e352" },
  { code: "B6", nameZh: "薄荷绿", hex: "#65e2a6" },
  { code: "B7", nameZh: "海绿", hex: "#3daf80" },
  { code: "B8", nameZh: "深翠", hex: "#1c9c4f" },
  { code: "B9", nameZh: "墨绿", hex: "#27523a" },
  { code: "B10", nameZh: "灰薄荷", hex: "#95d3c2" },
  { code: "B11", nameZh: "橄榄", hex: "#5d722a" },
  { code: "B12", nameZh: "松绿", hex: "#166f41" },
  { code: "B13", nameZh: "苹果绿", hex: "#caeb7b" },
  { code: "B14", nameZh: "鲜苹果绿", hex: "#ade946" },
  { code: "B15", nameZh: "森林绿", hex: "#2e5132" },
  { code: "B16", nameZh: "浅嫩绿", hex: "#c5ed9c" },
  { code: "B17", nameZh: "苔藓绿", hex: "#9bb13a" },
  { code: "B18", nameZh: "草黄", hex: "#e6ee49" },
  { code: "B19", nameZh: "翡翠绿", hex: "#24b88c" },
  { code: "B20", nameZh: "极浅绿", hex: "#c2f0cc" },
  { code: "B21", nameZh: "鸭嘴绿", hex: "#156a6b" },
  { code: "B22", nameZh: "深墨绿", hex: "#0b3c43" },
  { code: "B23", nameZh: "暗橄榄", hex: "#303a21" },
  { code: "B24", nameZh: "嫩米绿", hex: "#eefca5" },
  { code: "B25", nameZh: "灰绿", hex: "#4e846d" },
  { code: "B26", nameZh: "卡其黄", hex: "#8d7a35" },
  { code: "B27", nameZh: "米绿", hex: "#cce1af" },
  { code: "B28", nameZh: "薄荷", hex: "#9ee5b9" },
  { code: "B29", nameZh: "苹果黄绿", hex: "#c5e254" },
  { code: "B30", nameZh: "浅鲜绿", hex: "#e2fcb1" },
  { code: "B31", nameZh: "鲜嫩绿", hex: "#b0e792" },
  { code: "B32", nameZh: "黄苔", hex: "#9cab5a" },
  // C：蓝 / 青
  { code: "C1", nameZh: "极浅薄荷", hex: "#e8ffe7" },
  { code: "C2", nameZh: "浅水蓝", hex: "#a9f9fc" },
  { code: "C3", nameZh: "天蓝", hex: "#a0e2fb" },
  { code: "C4", nameZh: "海蓝", hex: "#41ccff" },
  { code: "C5", nameZh: "湖蓝", hex: "#01aceb" },
  { code: "C6", nameZh: "浅蓝", hex: "#50aaf0" },
  { code: "C7", nameZh: "蓝色", hex: "#3677d2" },
  { code: "C8", nameZh: "深蓝", hex: "#0f54c0" },
  { code: "C9", nameZh: "宝蓝", hex: "#324bca" },
  { code: "C10", nameZh: "孔雀蓝", hex: "#3ebce2" },
  { code: "C11", nameZh: "青色", hex: "#28ddde" },
  { code: "C12", nameZh: "藏蓝", hex: "#1c334d" },
  { code: "C13", nameZh: "婴儿蓝", hex: "#cde8ff" },
  { code: "C14", nameZh: "极浅冰蓝", hex: "#d5fdff" },
  { code: "C15", nameZh: "翠青", hex: "#22c4c6" },
  { code: "C16", nameZh: "深海蓝", hex: "#1557a8" },
  { code: "C17", nameZh: "亮蓝", hex: "#04d1f6" },
  { code: "C18", nameZh: "墨蓝", hex: "#1d3344" },
  { code: "C19", nameZh: "湖青", hex: "#1887a2" },
  { code: "C20", nameZh: "深湖蓝", hex: "#176daf" },
  { code: "C21", nameZh: "粉蓝", hex: "#beddff" },
  { code: "C22", nameZh: "灰蓝绿", hex: "#67b4be" },
  { code: "C23", nameZh: "雾蓝", hex: "#c8e2ff" },
  { code: "C24", nameZh: "浅天蓝", hex: "#7cc4ff" },
  { code: "C25", nameZh: "浅薄荷青", hex: "#a9e5e5" },
  { code: "C26", nameZh: "中蓝", hex: "#3caed8" },
  { code: "C27", nameZh: "淡紫蓝", hex: "#d3dffa" },
  { code: "C28", nameZh: "灰蓝", hex: "#bbcfed" },
  { code: "C29", nameZh: "深紫蓝", hex: "#34488e" },
  // D：紫
  { code: "D1", nameZh: "淡紫", hex: "#aeb4f2" },
  { code: "D2", nameZh: "浅紫", hex: "#858edd" },
  { code: "D3", nameZh: "蓝紫", hex: "#2f54af" },
  { code: "D4", nameZh: "深蓝紫", hex: "#182a84" },
  { code: "D5", nameZh: "紫罗兰", hex: "#b843c5" },
  { code: "D6", nameZh: "薰衣草", hex: "#ac7bde" },
  { code: "D7", nameZh: "中紫", hex: "#8854b3" },
  { code: "D8", nameZh: "极淡紫", hex: "#e2d3ff" },
  { code: "D9", nameZh: "粉紫", hex: "#d5b9f8" },
  { code: "D10", nameZh: "深紫", hex: "#361851" },
  { code: "D11", nameZh: "灰紫", hex: "#b9bae1" },
  { code: "D12", nameZh: "浅粉紫", hex: "#de9ad4" },
  { code: "D13", nameZh: "玫红", hex: "#b90095" },
  { code: "D14", nameZh: "葡萄紫", hex: "#8b279b" },
  { code: "D15", nameZh: "靛紫", hex: "#2f1f90" },
  { code: "D16", nameZh: "极浅灰紫", hex: "#e3e1ee" },
  { code: "D17", nameZh: "淡灰蓝", hex: "#c4d4f6" },
  { code: "D18", nameZh: "紫红", hex: "#a45ec7" },
  { code: "D19", nameZh: "灰粉紫", hex: "#d8c3d7" },
  { code: "D20", nameZh: "葡萄", hex: "#9c32b2" },
  { code: "D21", nameZh: "紫色", hex: "#9a009b" },
  { code: "D22", nameZh: "深靛蓝", hex: "#333a95" },
  { code: "D23", nameZh: "浅淡紫", hex: "#ebdafc" },
  { code: "D24", nameZh: "淡蓝紫", hex: "#7786e5" },
  { code: "D25", nameZh: "靛蓝", hex: "#494fc7" },
  { code: "D26", nameZh: "浅薰衣草", hex: "#dfc2f8" },
  // E：粉
  { code: "E1", nameZh: "浅粉", hex: "#fdd3cc" },
  { code: "E2", nameZh: "粉霞", hex: "#fec0df" },
  { code: "E3", nameZh: "亮粉", hex: "#ffb7e7" },
  { code: "E4", nameZh: "桃红", hex: "#e8649e" },
  { code: "E5", nameZh: "玫瑰粉", hex: "#f551a2" },
  { code: "E6", nameZh: "玫红", hex: "#f13d74" },
  { code: "E7", nameZh: "紫莓", hex: "#c63478" },
  { code: "E8", nameZh: "浅樱", hex: "#ffdbe9" },
  { code: "E9", nameZh: "品红粉", hex: "#e970cc" },
  { code: "E10", nameZh: "玫粉", hex: "#d33793" },
  { code: "E11", nameZh: "浅奶粉", hex: "#fcddd2" },
  { code: "E12", nameZh: "粉红", hex: "#f78fc3" },
  { code: "E13", nameZh: "深玫红", hex: "#b5006d" },
  { code: "E14", nameZh: "杏粉", hex: "#ffd1ba" },
  { code: "E15", nameZh: "浅樱粉", hex: "#f8c7c9" },
  { code: "E16", nameZh: "暖奶白", hex: "#fff3eb" },
  { code: "E17", nameZh: "极浅粉", hex: "#ffe2ea" },
  { code: "E18", nameZh: "浅桃粉", hex: "#ffc7db" },
  { code: "E19", nameZh: "粉藕", hex: "#febad5" },
  { code: "E20", nameZh: "灰粉", hex: "#d8c7d1" },
  { code: "E21", nameZh: "藕灰", hex: "#bd9da1" },
  { code: "E22", nameZh: "烟粉紫", hex: "#b785a1" },
  { code: "E23", nameZh: "灰紫藕", hex: "#937a8d" },
  { code: "E24", nameZh: "浅丁香", hex: "#e1bce8" },
  // F：红
  { code: "F1", nameZh: "珊瑚", hex: "#fd957b" },
  { code: "F2", nameZh: "鲜红", hex: "#fc3d46" },
  { code: "F3", nameZh: "大红", hex: "#f74941" },
  { code: "F4", nameZh: "正红", hex: "#fc283c" },
  { code: "F5", nameZh: "红色", hex: "#e7002f" },
  { code: "F6", nameZh: "暗红", hex: "#943630" },
  { code: "F7", nameZh: "酒红", hex: "#971937" },
  { code: "F8", nameZh: "深红", hex: "#bc0028" },
  { code: "F9", nameZh: "西瓜红", hex: "#e2677a" },
  { code: "F10", nameZh: "棕红", hex: "#8a4526" },
  { code: "F11", nameZh: "深棕红", hex: "#5a2121" },
  { code: "F12", nameZh: "玫瑰红", hex: "#fd4e6a" },
  { code: "F13", nameZh: "番茄红", hex: "#f35744" },
  { code: "F14", nameZh: "浅珊瑚", hex: "#ffa9ad" },
  { code: "F15", nameZh: "深正红", hex: "#d30022" },
  { code: "F16", nameZh: "浅杏", hex: "#fec2a6" },
  { code: "F17", nameZh: "陶土橙", hex: "#e69c79" },
  { code: "F18", nameZh: "赭橙", hex: "#d37c46" },
  { code: "F19", nameZh: "砖红", hex: "#c1444a" },
  { code: "F20", nameZh: "灰玫", hex: "#cd9391" },
  { code: "F21", nameZh: "浅玫粉", hex: "#f7b4c6" },
  { code: "F22", nameZh: "淡粉", hex: "#fdc0d0" },
  { code: "F23", nameZh: "橙红", hex: "#f67e66" },
  { code: "F24", nameZh: "豆沙粉", hex: "#e698aa" },
  { code: "F25", nameZh: "红珊瑚", hex: "#e54b4f" },
  // G：棕 / 驼
  { code: "G1", nameZh: "浅肤", hex: "#ffe2ce" },
  { code: "G2", nameZh: "肤色", hex: "#ffc4aa" },
  { code: "G3", nameZh: "浅驼", hex: "#f4c3a5" },
  { code: "G4", nameZh: "驼色", hex: "#e1b383" },
  { code: "G5", nameZh: "芥黄", hex: "#edb045" },
  { code: "G6", nameZh: "琥珀", hex: "#e99c17" },
  { code: "G7", nameZh: "棕色", hex: "#9d5b3e" },
  { code: "G8", nameZh: "深棕", hex: "#753832" },
  { code: "G9", nameZh: "浅棕", hex: "#e6b483" },
  { code: "G10", nameZh: "焦糖", hex: "#d98c39" },
  { code: "G11", nameZh: "卡其", hex: "#e0c593" },
  { code: "G12", nameZh: "杏黄", hex: "#ffc890" },
  { code: "G13", nameZh: "红棕", hex: "#b7714a" },
  { code: "G14", nameZh: "咖啡棕", hex: "#8d614c" },
  { code: "G15", nameZh: "米白", hex: "#fcf9e0" },
  { code: "G16", nameZh: "奶咖", hex: "#f2d9ba" },
  { code: "G17", nameZh: "深褐", hex: "#78524b" },
  { code: "G18", nameZh: "浅奶杏", hex: "#ffe4cc" },
  { code: "G19", nameZh: "赭石", hex: "#e07935" },
  { code: "G20", nameZh: "砖棕", hex: "#a94023" },
  { code: "G21", nameZh: "浅咖", hex: "#b88558" },
  // H：白 / 灰 / 黑
  { code: "H1", nameZh: "纯白", hex: "#fdfbff" },
  { code: "H2", nameZh: "净白", hex: "#feffff" },
  { code: "H3", nameZh: "灰色", hex: "#b6b1ba" },
  { code: "H4", nameZh: "中灰", hex: "#89858c" },
  { code: "H5", nameZh: "深灰", hex: "#48464e" },
  { code: "H6", nameZh: "炭灰", hex: "#2f2b2f" },
  { code: "H7", nameZh: "黑色", hex: "#000000" },
  { code: "H8", nameZh: "粉白", hex: "#e7d6db" },
  { code: "H9", nameZh: "浅灰", hex: "#ededed" },
  { code: "H10", nameZh: "珍珠白", hex: "#eee9ea" },
  { code: "H11", nameZh: "银灰", hex: "#cecdd5" },
  { code: "H12", nameZh: "象牙白", hex: "#fff5ed" },
  { code: "H13", nameZh: "米白", hex: "#f5ecd2" },
  { code: "H14", nameZh: "灰绿白", hex: "#cfd7d3" },
  { code: "H15", nameZh: "灰蓝绿", hex: "#98a6a8" },
  { code: "H16", nameZh: "墨黑", hex: "#1d1414" },
  { code: "H17", nameZh: "暖白", hex: "#f1eded" },
  { code: "H18", nameZh: "乳白", hex: "#fffdf0" },
  { code: "H19", nameZh: "米灰白", hex: "#f6efe2" },
  { code: "H20", nameZh: "蓝灰", hex: "#949fa3" },
  { code: "H21", nameZh: "浅鹅黄白", hex: "#fffbe1" },
  { code: "H22", nameZh: "浅银灰", hex: "#cacad4" },
  { code: "H23", nameZh: "灰绿", hex: "#9a9d94" },
  // M：灰调
  { code: "M1", nameZh: "灰绿", hex: "#bcc6b8" },
  { code: "M2", nameZh: "橄榄灰绿", hex: "#8aa386" },
  { code: "M3", nameZh: "灰青", hex: "#697d80" },
  { code: "M4", nameZh: "米驼", hex: "#e3d2bc" },
  { code: "M5", nameZh: "灰米", hex: "#d0ccaa" },
  { code: "M6", nameZh: "灰卡其", hex: "#b0a782" },
  { code: "M7", nameZh: "灰褐", hex: "#b4a497" },
  { code: "M8", nameZh: "灰玫", hex: "#b38281" },
  { code: "M9", nameZh: "灰棕", hex: "#a58767" },
  { code: "M10", nameZh: "灰紫粉", hex: "#c5b2bc" },
  { code: "M11", nameZh: "灰紫", hex: "#9f7594" },
  { code: "M12", nameZh: "深褐灰", hex: "#644749" },
  { code: "M13", nameZh: "浅赭", hex: "#d19066" },
  { code: "M14", nameZh: "砖粉", hex: "#c77362" },
  { code: "M15", nameZh: "中性灰", hex: "#757d78" },
  // P：杂色
  { code: "P1", nameZh: "雪白", hex: "#fcf7f8" },
  { code: "P2", nameZh: "灰色", hex: "#b0a9ac" },
  { code: "P3", nameZh: "浅绿", hex: "#afdcab" },
  { code: "P4", nameZh: "浅珊瑚", hex: "#fea49f" },
  { code: "P5", nameZh: "橙色", hex: "#ee8c3e" },
  { code: "P6", nameZh: "薄荷绿", hex: "#5fd0a7" },
  { code: "P7", nameZh: "橙粉", hex: "#eb9270" },
  { code: "P8", nameZh: "鹅黄", hex: "#f0d958" },
  { code: "P9", nameZh: "浅灰", hex: "#d9d9d9" },
  { code: "P10", nameZh: "浅紫", hex: "#d9c7ea" },
  { code: "P11", nameZh: "米黄", hex: "#f3ecc9" },
  { code: "P12", nameZh: "冰蓝白", hex: "#e6eef2" },
  { code: "P13", nameZh: "浅天蓝", hex: "#aacbef" },
  { code: "P14", nameZh: "深青", hex: "#337680" },
  { code: "P15", nameZh: "灰绿", hex: "#668575" },
  { code: "P16", nameZh: "金黄", hex: "#febf45" },
  { code: "P17", nameZh: "橙黄", hex: "#fea324" },
  { code: "P18", nameZh: "杏粉", hex: "#feb89f" },
  { code: "P19", nameZh: "乳白", hex: "#fffeec" },
  { code: "P20", nameZh: "粉色", hex: "#febecf" },
  { code: "P21", nameZh: "藕粉", hex: "#ecbebf" },
  { code: "P22", nameZh: "豆沙", hex: "#e4a89f" },
  { code: "P23", nameZh: "暗玫", hex: "#a56268" },
  // Q
  { code: "Q1", nameZh: "粉紫", hex: "#f2a5e8" },
  { code: "Q2", nameZh: "嫩黄绿", hex: "#e9ec91" },
  { code: "Q3", nameZh: "正黄", hex: "#ffff00" },
  { code: "Q4", nameZh: "浅粉白", hex: "#ffebfa" },
  { code: "Q5", nameZh: "天青", hex: "#76cede" },
  // R
  { code: "R1", nameZh: "红色", hex: "#d50d21" },
  { code: "R2", nameZh: "玫红", hex: "#f92f83" },
  { code: "R3", nameZh: "橙色", hex: "#fd8324" },
  { code: "R4", nameZh: "柠黄", hex: "#f8ec31" },
  { code: "R5", nameZh: "绿色", hex: "#35c75b" },
  { code: "R6", nameZh: "青绿", hex: "#238891" },
  { code: "R7", nameZh: "湖蓝", hex: "#19779d" },
  { code: "R8", nameZh: "蓝色", hex: "#1a60c3" },
  { code: "R9", nameZh: "紫色", hex: "#9a56b4" },
  { code: "R10", nameZh: "黄色", hex: "#ffdb4c" },
  { code: "R11", nameZh: "粉白", hex: "#ffebfa" },
  { code: "R12", nameZh: "灰白", hex: "#d8d5ce" },
  { code: "R13", nameZh: "深灰", hex: "#55514c" },
  { code: "R14", nameZh: "浅青", hex: "#9fe4df" },
  { code: "R15", nameZh: "浅蓝", hex: "#77cee9" },
  { code: "R16", nameZh: "青色", hex: "#3ecfca" },
  { code: "R17", nameZh: "墨绿青", hex: "#4a867a" },
  { code: "R18", nameZh: "薄荷", hex: "#7fcd9d" },
  { code: "R19", nameZh: "黄绿", hex: "#cde55d" },
  { code: "R20", nameZh: "浅驼", hex: "#e8c7b4" },
  { code: "R21", nameZh: "棕色", hex: "#ad6f3c" },
  { code: "R22", nameZh: "深棕", hex: "#6c372f" },
  { code: "R23", nameZh: "杏橙", hex: "#feb872" },
  { code: "R24", nameZh: "浅粉", hex: "#f3c1c0" },
  { code: "R25", nameZh: "砖红", hex: "#c9675e" },
  { code: "R26", nameZh: "藕紫", hex: "#d293be" },
  { code: "R27", nameZh: "粉色", hex: "#ea8cb1" },
  { code: "R28", nameZh: "浅紫", hex: "#9c87d6" },
  // Y
  { code: "Y1", nameZh: "粉红", hex: "#fd6fb4" },
  { code: "Y2", nameZh: "杏橙", hex: "#feb481" },
  { code: "Y3", nameZh: "浅黄绿", hex: "#d7faa0" },
  { code: "Y4", nameZh: "浅蓝", hex: "#8bdbfa" },
  { code: "Y5", nameZh: "粉紫", hex: "#e987ea" },
  // ZG：灰调系列
  { code: "ZG1", nameZh: "灰粉", hex: "#daabb3" },
  { code: "ZG2", nameZh: "驼色", hex: "#d6aa87" },
  { code: "ZG3", nameZh: "灰黄绿", hex: "#c1bd8d" },
  { code: "ZG4", nameZh: "灰紫", hex: "#96869f" },
  { code: "ZG5", nameZh: "灰蓝", hex: "#8490a6" },
  { code: "ZG6", nameZh: "雾蓝", hex: "#94bfe2" },
  { code: "ZG7", nameZh: "灰粉紫", hex: "#e2a9d2" },
  { code: "ZG8", nameZh: "灰紫", hex: "#ab91c0" }
];

export const MARD_PALETTE = preparePalette(MARD_PALETTE_SEEDS);
